### ISSUE TITLE
The "\" character is doubled when copied

### ISSUE THREAD

**Issue by AlexValue** [oae/gnome-shell-pano#307] opened 2024-07-28 21:39 UTC
## Description

The "\\" character is doubled when using the extension in certain ways.

### Problem Explanation

The "\\" symbol is doubled when called multiple times from the Pano clipboard history. To make the bug appear, you need to alternate calls to "\\" and any other text.

### Expected Behavior

Pano should not double the "\\" character. Instead, the character should be copied unchanged.

### Steps To Reproduce

1. Copy "\\" to the clipboard
2. Copy "Any text" to the clipboard.
3. Open the clipboard history in Pano
4. Select the saved entry "\\"
5. Open the clipboard history in Pano again
6. At this point, you see that the entry "\\" in the Pano clipboard history has turned into "\\\\"

### Details

Mark with [ ] all that applies:

#### It happens with any application?

- [x] Yes, it applies to any application.
- [ ] No. Only with the following applications:
  - VSCode
- [ ] It works with the following applications that I have tried:
  - Fill in a list with any application that applies

#### It happens only on one computer?

- [x] I don't know.
- [ ] No. I have tried it on more than one computer.

#### It happens only with some specific gnome configuration?

- [x] I don't think that the configuration matters.
- [ ] Yes. Only if the following config is set up:
  - Fill in a list with any configuration tha applies.

#### It happens only with some specific extension installed?

- [x] I don't think that the installed extensions affect the bug/behavior.
- [ ] Yes. Only if the following gnome extension is installed:
  - Fill in a list with any extension tha applies.
  - Fill in also any detail about the extensions that applies.

### Environment

- GNOME Shell version: 45.8.1
- Distro: Fedora
- Distro version: 39.20240721.0 (Silverblue)

#### What is pasted, if applicable

``` text
\
```

``` text
Any text
```

#### Application Version

``` bash
$ app --version  # 59
1.74.3
```

**Comment by Totto16** [comment] 2024-07-28 21:58
This is a duplicate of #196 and #107 and is fixed in #266. 
Unfortunately we haven't published a version with this fix on EGO, so you need to install the extension manually, to get the bugfix. See [here](https://github.com/oae/gnome-shell-pano?tab=readme-ov-file#development) for some instructions (or [here](https://github.com/oae/gnome-shell-pano/issues/271#issuecomment-2147145350) )

**Closed** 2024-07-28 21:58 UTC
Labels: bug, duplicate
