### ISSUE TITLE
Pressing Esc after search should clear search

### ISSUE THREAD

**Issue by forteller** [oae/gnome-shell-pano#89] opened 2022-09-18 21:36 UTC
In most applications, pressing Esc after doing a search closes the search box. In Pano the whole "application" closes instead. This breaks expectation, IMO. I'd much rather the first Esc clear the search box, and then you'd press Esc a second time to close Pano.

Thanks! :)

**Comment by oae** [comment] 2022-09-18 21:38
Esc closes the window by design. You can just press backspace anywhere on the pano. Or if you want to focus on the search box just press the up arrow key.

**Comment by forteller** [comment] 2022-09-18 21:47
Thanks for your fast reply!

I understand that it's by design. What I'm saying is that in my experience this is very uncommon, thus it breaks peoples expectations, and so I feel like it should be changed. 

The shortcut most people will use for opening Pano is in the lower left corner of the keyboard, and from there the Esc key is much closer than the backspace in the top right corner of the keyboard, in addition having one key to press to remove the whole word you searched for instead of having to press Backspace multiple times to remove all the letters one by one is also very useful, IMHO.

Let's say you search for the word "test", only to not find what you where looking for. Now you have to press Backspace four times before you can start typing a new word to search for, instead of just pressing Esc once and then start typing the new word.

**Comment by oae** [comment] 2022-09-18 21:47
Also, you can clear the search by disabling the keep search entry in the settings.

![image](https://user-images.githubusercontent.com/1043714/190929272-c2109311-0166-4357-9c5a-1cd9f5ed94e3.png)

**Comment by oae** [comment] 2022-09-18 21:50
If we have more feedback from people about this, I would consider this.

**Comment by forteller** [comment] 2022-09-18 21:53
> Also, you can clear the search by disabling the keep search entry in the settings.

That's good to know, I hadn't seen that. I think that should be turned off by default. Still, I feel that my feature request would be good to implement. But I understand your need to get more feedback on this. Thanks for having an open mind :)

**Comment by MuhametSmaili** [comment] 2022-09-22 05:16
This can be a feature if you want to implement it, but not a default one. I never expect `ESC` to clear my input. 
I always expect `ESC`  to close it.

**Comment by forteller** [comment] 2022-09-22 10:00
Yes, close the input, which normally clears the input, right? But since the input is always visible in Pano, then just clearing it is the same as closing it. Look at Gnome Activities view as an example. The input is always visible, you start to type, and when you press Esc you clear the input and go back to the "blank" Activities view. So the first press of Esc after typing something "closes" the input, but since the input is always visible it only clears it. Then the second Esc closes the Activities view. If the first Esc after typing something closed the Activities view completely and sent you back to your previous state, wouldn't that be confusing? That's what Pano does now, and even if it's not confusing to you, then at least it's not in line with how Gnome does things.

**Closed** 2023-03-04 22:12 UTC
Labels: enhancement, need-feedback
