### ISSUE TITLE
Show current copied content on top panel

### ISSUE THREAD

**Issue by motmaytinh** [oae/gnome-shell-pano#175] opened 2023-03-23 09:51 UTC
**Is your feature request related to a problem? Please describe.**
I don't remember what text, url or photo that I currently copy.

**Describe the solution you'd like**
It would be nice to show some first characters of the text being copied.

**Describe alternatives you've considered**
Open up pano to see the first item.

**Additional context**
![image](https://user-images.githubusercontent.com/18485039/227166086-af26191e-36ef-49b9-a3ce-3f6d4b7a7af2.png)

**Comment by oae** [comment] 2023-03-23 10:43
Duplicate of https://github.com/oae/gnome-shell-pano/issues/110

**Closed by oae** 2023-03-23 10:43 UTC
Labels: enhancement
