### ISSUE TITLE
Repeated backslash escape

### ISSUE THREAD

**Issue by analytic-bias** [oae/gnome-shell-pano#196] opened 2023-05-26 02:28 UTC
## Description

**What is the bug?**

Repeated backslash escape

### Problem Explanation

Write a clear and concise description of what the bug is:

The bug happens when one tries to copy a text with backslashes.

### Expected Behavior

A clear and concise description of what you expected to happen, and how the actual outcome differs:

- Pano shouldn't repeatedly apply character backslash escapes, as in
![image](https://github.com/oae/gnome-shell-pano/assets/6694864/eb591de3-bb99-402f-8632-d96459a01281)

- It should behave correctly when copying and pasting text with backslash characters.

## Reprodution

**How one can find the bug?**

### Steps To Reproduce

Steps to reproduce, if applicable:

1. Copy this text:
```latex
\( X^*(T)^{\vee} = \mathbb{Z}^r \)
```
2. Open the clipboard history.
3. Optionally repeat

### Details

Mark with [ ] all that applies:

#### It happens with any application?

- [x] Yes, it applies to any application.
- [ ] No. Only with the following applications:
  - VSCode
- [ ] It works with the following applications that I have tried:
  - Fill in a list with any application that applies

#### It happens only on one computer?

- [x] I don't know.
- [ ] No. I have tried it on more than one computer.

#### It happens only with some specific gnome configuration?

- [x] I don't think that the configuration matters.
- [ ] Yes. Only if the following config is set up:
  - Fill in a list with any configuration tha applies.

#### It happens only with some specific extension installed?

- [x] I don't think that the installed extensions affect the bug/behavior.
- [ ] Yes. Only if the following gnome extension is installed:
  - Fill in a list with any extension tha applies.
  - Fill in also any detail about the extensions that applies.

## Diagnostics

**Under what conditions does it happen?**

Fill in all information that applies:

### Environment

![image](https://github.com/oae/gnome-shell-pano/assets/6694864/88699492-193b-4bab-bd72-c25aa3a43fda)

**Comment by Totto16** [comment] 2023-10-31 12:52
Duplicate (but still not fixed)  of #107

**Comment by e2ipi-1** [comment] 2024-02-03 18:30
Here's the method I'm using to overcome this problem while awaiting a more serious repair from the developers, and which gives good results with the "Ubuntu 23.10/GNOME 45.2/Pano 22" configuration.

The idea is to "externally" restore the pano.db database after each modification. Two situations can be distinguished: 0) a new entry; 1) an entry has been modified by the extension.

**Warning**: in the following, `<USER>` refers to the user name.

# Requirement
_incron_
`sudo apt install incron`

_sqlite3_
`sudo apt install sqlite3`

# Method
a) Modify the `~/.local/share/gnome-shell/extensions/pano@elhan.io/extension.js` file (after saving it) according to the attached `extension.js.diff.txt` file. You can place this file in `~/.local/share/gnome-shell/extensions/pano@elhan.io` and run:

```
cp extension.js extension.js.bak
patch -i extension.js.diff.txt extension.js
```
[extension.js.diff.txt](https://github.com/oae/gnome-shell-pano/files/14152379/extension.js.diff.txt)

b) Delete the `~/.local/share/pano@elhan.io` folder. 
**Warning**: all clipboard contents will be permanently lost.

c) Restart the machine. 

d) The `~/.local/share/pano@elhan.io` folder has been recreated and the `pano.db` database it contains shows a new `changeType` column added at the end, intended to receive 3 numerical values: `0` for a new entry; `1` for an entry modified by the extension; `2` for an entry modified externally by sqlite3 as we shall see.

e) Create the script `~/.local/bin/pano-modify_database.sh` and make it executable:

```
#!/bin/bash

sleep 0.1

cd /home/<USER>/.local/share/pano@elhan.io

sqlite3 pano.db << EOF
UPDATE clipboard SET content = REPLACE(content,'\\\\','\\') WHERE changeType = 0 OR changeType = 1;
UPDATE clipboard SET matchValue = REPLACE(matchValue,'\\\\','\\') WHERE changeType = 1;
UPDATE clipboard SET searchValue = REPLACE(searchValue,'\\\\','\\') WHERE changeType = 1;
UPDATE clipboard SET changeType = 2;
EOF

incrontab -d
```
f) Finally, configure incron :
`sudo nano /etc/incron.allow`
then type `<USER>` then `ctrl+S` and `ctrl+X` then
`incrontab -e`
type
`/home/<USER>/.local/share/pano@elhan.io/pano.db  IN_MODIFY,IN_ONESHOT  /home/<USER>/.local/bin/pano-modify_database.sh`
(**warning**: the 2 spaces that appear must be filled by pressing the Tab key)
then type  `ctrl+S` and `ctrl+X`.

# Remarks
i) This method doesn't work properly with the "Ubuntu 22.04.3/GNOME 42.9/Pano 19" configuration, I've no idea why.

ii) Not having mastered GJS at all, the changes made to the `extensions.js` file dealing with the new `changeType` column are certainly not optimal. Let's just say that it seems to work like that for my use of Pano, so any improvements are welcome!

iii) Be careful when deleting the history. When the `~/.local/share/pano@elhan.io` folder is deleted, the incron table must be reloaded via `incrontab -d` once this folder has been recreated.
Note that on my system, deleting the history causes problems: the `~/.local/share/pano@elhan.io` folder is deleted but not recreated, either from the indicator or from the settings panel...

iv) Here's how I've gone about it so that everything is automatic and seems to work correctly, bearing in mind that I only clear the history from the Pano indicator:

* Another modification to the `~/.local/share/gnome-shell/extensions/pano@elhan.io/extension.js` file: replace `stop()` with `disable()` and `start()` with `enable()` in the definition of the `clearHistory()` function.

* Restart.

* Creation of script `~/.local/bin/pano-reload_incrontab.sh` made executable:

```
#!/bin/bash

sleep 3
incrontab -d
```

* Update incron table to monitor possible deletion of `pictures` folder contained in `~/.local/share/pano@elhan.io` :
`incrontab -e`
type
`/home/<USER>/.local/share/pano@elhan.io/pictures  IN_DELETE_SELF,IN_ONESHOT  /home/<USER>/.local/bin/pano-reload_incrontab.sh`
then `ctrl+S` and `ctrl+X`.

v) The contents of the database can be viewed at any time via 
```
sqlite3 ~/.local/share/pano@elhan.io/pano.db
SELECT * FROM clipboard;
```

**Comment by Totto16** [comment] 2024-03-26 01:28
The error is indeed what @NinZeige discovered, thank you for that :heart:
And the fix is to just unescape the content on reading it from the db (see #266) , it may have issues, even if I tested it with some `\` heavy files (some latex files, it was really annoying to copy things there with this issue 😓 )

@analytic-bias  @NinZeige
It would really help if you tested it locally, by following the steps in the [README](https://github.com/oae/gnome-shell-pano?tab=readme-ov-file#development) ❤️

**Comment by e2ipi-1** [comment] 2024-03-26 09:34
@Totto16 Although I was not invited to do so, I was able to test your proposal. 

I made the modifications indicated in the `extension.js` file. Getting an error on my "Ubuntu 23.10/GNOME 45.2/Pano 22" system, I replaced "Gda5.default_unescape_string" with "Gda.default_unescape_string".

That said, Pano's operation around backslash is improving and looking more like it should, but problems remain. For example:

1. Copy `\test1` then `\test2`.
2. Open the panel and paste `\test1`.
3. Open panel and paste `\test2`.
4. Open panel and paste `\test1`.
5. Finally, open the panel and observe a duplicate `\test1`.

For the time being, I'll continue with the _incron_ DIY I described above, which seems to be more robust.

Best regards

**Comment by Totto16** [comment] 2024-03-26 14:05
> @Totto16 Although I was not invited to do so, I was able to test your proposal.
> 
> I made the modifications indicated in the `extension.js` file. Getting an error on my "Ubuntu 23.10/GNOME 45.2/Pano 22" system, I replaced "Gda5.default_unescape_string" with "Gda.default_unescape_string".
> 
> That said, Pano's operation around backslash is improving and looking more like it should, but problems remain. For example:
> 
>     1. Copy `\test1` then `\test2`.
> 
>     2. Open the panel and paste `\test1`.
> 
>     3. Open panel and paste `\test2`.
> 
>     4. Open panel and paste `\test1`.
> 
>     5. Finally, open the panel and observe a duplicate `\test1`.
> 
> 
> For the time being, I'll continue with the _incron_ DIY I described above, which seems to work better.
> 
> Best regards

The name GDa5 just comes from the import name of `import Gda5 from '@girs/gda-5.0';` but at transpile time from rollup it gets converted to `import Gda5 from 'gi://Gda?version>=5.0';` so thats just a name, that get's associat6ed with gda, since we use 5.0 types here, but support both 6.0 and 5.0

That said, I mentioned you in the Issue #107 and didn't want to mention you twice 😓 😂 

I will look into this issue and see, if it can be solved, since the other solution is not that easy to do as a new user and this issue should be fixed in the extnesion itself, thnak you for your testing ❤️

**Comment by Totto16** [comment] 2024-03-26 15:36
Ah yes, that seems 

> Thank you for your message and this clarification about Gda5.
> 
> I was able to do some more tests. Taking up your idea around "matchValue" and "searchValue", the situation seems to improve: the problem I mentioned earlier disappears and more generally, the database seems to behave as it should. More precisely, I've modified my `extension.js` file as follows (in the places indicated):
> 
> ```
> + const content_unescaped = Gda.default_unescape_string(content) ?? content;
> + const matchValue_unescaped = Gda.default_unescape_string(matchValue) ?? matchValue;
> + const searchValue_unescaped = Gda.default_unescape_string(searchValue) ?? searchValue;
> 
> - content,
> + content: content_unescaped,
> - matchValue,
> + matchValue: matchValue_unescaped,
> - searchValue,
> + searchValue: searchValue_unescaped,
> ```
> 
> Acting at the level of the extension itself is of course the right method.
> 
> Thank you for your work on Pano, especially on the switch to GNOME 45 and on this major problem. 👍

Ah yes, that seems a good idea, I already said, that there might be potential other fields, where unescaping is needed, I never save the search value or match value, so it's clear, why I never caught that bug. I'll test that myself later 👍🏼 Thank you too, for testing this ❤️

**Comment by e2ipi-1** [comment] 2024-03-26 16:12
Unfortunately, this leads to other problems. I just got an "Argument string may not be null" error, which forced me to clear the history to be able to restart the extension. To reproduce :

1. Take a screenshot to obtain an image in the clipboard.
2. Bring up the panel and click on the favorites star in the search bar.
3. Click again on the favorites star in the search bar.
4. The image has disappeared from the panel and restarting a session gives the error message.

If it helps. That's all for today!

**Comment by Totto16** [comment] 2024-03-26 16:53
> Unfortunately, this leads to other problems. I just got an "Argument string may not be null" error, which forced me to clear the history to be able to restart the extension. To reproduce :
> 
>     1. Take a screenshot to obtain an image in the clipboard.
> 
>     2. Bring up the panel and click on the favorites star in the search bar.
> 
>     3. Click again on the favorites star in the search bar.
> 
>     4. The image has disappeared from the panel and restarting a session gives the error message.
> 
> 
> If it helps. That's all for today!

Yes that helps ❤️ 
I'll look into it, I think i might know the cause of that issues 👍🏼

**Closed** 2024-05-30 20:28 UTC
Labels: bug
