### ISSUE TITLE
Shortcuts and navigation not working after update

### ISSUE THREAD

**Issue by MohammadMD1383** [oae/gnome-shell-pano#69] opened 2022-09-12 05:36 UTC
**Describe the bug**
shortcuts not working, also when clipboard is shown (using tray icon) I cannot use <kbd>Right Arrow</kbd> or <kbd>Left Arrow</kbd> to navigate.

**Expected behavior**
Everything should work fine.

**Screenshots**
![image](https://user-images.githubusercontent.com/69088224/189580170-42ad6c70-b31f-4d90-9b92-9fea5098415c.png)

**To Reproduce**
- GNOME Shell version: 42
- Distro: Ubuntu 22.04
- Steps to reproduce, if applicable:
1. Update the extension
2. Bugs happened (before updating everything was working...)

**Log data**
Output from `journalctl /usr/bin/gnome-shell`:
```

```

**Comment by oae** [comment] 2022-09-12 06:39
I am not able to reproduce this. Can you reset the settings with `dconf reset -f /org/gnome/shell/extensions/pano/` and logout/login again?

**Comment by doppelhelix** [comment] 2022-09-12 06:57
Did a dconf reset as mentioned. No luck.

**Comment by oae** [comment] 2022-09-12 07:14
I even tried to follow the update path of the extension. Still could not reproduce this. Are there any logs in `journalctl`?

**Comment by oae** [comment] 2022-09-12 07:44
Maybe try removing and installing the extension again.

**Comment by DuttaAB-dev** [comment] 2022-09-12 07:50
Same issue here. Assigned shortcut does not work

**Comment by DuttaAB-dev** [comment] 2022-09-12 08:40
Uninstalled and then reinstalled the extension, but the issue still remains.
![image](https://user-images.githubusercontent.com/61903332/189610031-ef9599ff-a692-4d9a-bb58-e4cd3dedd944.png)

**Comment by DuttaAB-dev** [comment] 2022-09-12 08:40
Worth noting that the incognito mode shortcut does work.

**Comment by oae** [comment] 2022-09-12 08:42
Can you reassign another shortcut for the toggle and see if that works

**Comment by muhammadyusuf-kurbonov** [comment] 2022-09-12 08:45
It does not work on my device too. 
OS: Fedora 36
Gnome 42
Navigation works, but shortcut not

**Comment by DuttaAB-dev** [comment] 2022-09-12 08:45
> Can you reassign another shortcut for the toggle and see if that works

Tried, still nothing.

**Comment by oae** [comment] 2022-09-12 09:15
Can you try the new release? https://github.com/oae/gnome-shell-pano/releases/tag/v8

**Comment by MohammadMD1383** [comment] 2022-09-12 09:33
> Can you try the new release? https://github.com/oae/gnome-shell-pano/releases/tag/v8

Thanks. That works fine

**Comment by oae** [comment] 2022-09-12 10:09
It should be working now with version v9

**Closed by oae** 2022-09-12 10:09 UTC
Labels: bug
